### ISSUE TITLE
Won't install R

### ISSUE THREAD

**Issue by gvegayon** [krlmlr/r-appveyor#64]
Hi, I get the following error 

> 'travis-tool.sh' is not recognized as an internal or external command,
operable program or batch file.

Here is the log
https://ci.appveyor.com/project/gvegayon/netdiffuser/build/1.0.107

**Comment by masalmon** [comment]
Oh, I have this issue too. The error is before the Travis message, it's

```
== 05/07/2016 06:38:38: Running R installer 
This command cannot be run due to the error: The file or directory is corrupted and unreadable.
```

The builds are:

* https://ci.appveyor.com/project/masalmon/ropenaq-84qm3/build/1.0.2/job/o765nms889llbef7

* https://ci.appveyor.com/project/masalmon/opencage

In ropenaq config file I have

```
  matrix:
  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: patched
```

and in opencage the default options.

Maybe it's just a problem on Appveyor that'll get resolved soon?

**Comment by krlmlr** [comment]
It's been like this for the last three days now (https://ci.appveyor.com/project/krlmlr/r-appveyor/history), but only for R-release and R-patched. Looking into it.

**Comment by krlmlr** [comment]
I think it's an rversions problem, see link above.

**Comment by krlmlr** [comment]
Please try again, and comment here if it still doesn't work.

**Comment by gvegayon** [comment]
Fixed, thanks!

**Comment by Fazendaaa** [comment]
Hey, pulling this issue out of nowhere... But, I'm having the same issue as you, guys. But I think this might be some issue related to changing directories. I've tried to change this "cd" script from before_build to before_test, still not working. This is the output: https://ci.appveyor.com/project/Fazendaaa/project-euler/build/1.0.14

**Comment by krlmlr** [comment]
Could you please file a new issue?

**Comment by Fazendaaa** [comment]
@krlmlr, of course.

**Comment by IndrajeetPatil** [comment]
I am having the same issue:
https://ci.appveyor.com/project/IndrajeetPatil/pairwisecomparisons/build/job/6eawsjja9to2i4hx

![image](https://user-images.githubusercontent.com/11330453/65035651-04a15500-d94a-11e9-9950-c3c4b1990dfc.png)
